### PR TITLE
Issue6

### PR DESCRIPTION
**Pull request by gbeane**
more correct fix for issue #6 

this ensures all features are loaded from previously computed hdf5 file. This way, when recomputing window features, we have all necessary features to compute all of the window features supported by a given pose file (even if the current project doesn't use all of those features)

### CODE REVIEW

**Comment by gbeane** [comment]
sorry @gerring, there are no tests added by this PR. This is about the max amount of effort that I can spend on this. Maybe a good intern project to mock everything up needed to add good unit test coverage for every class...

**Comment by gbeane** [comment]
last PR fixed the exception Leinani was seeing adding a new window size via the GUI, but the newly generated window feature files only included features enabled in the current project. When adding additional window sizes using the command line script, the resulting window feature files contained all features supported for a given pose files, even if some of those features are unused by the current project. This change now matches that behavior when adding new window sizes in the GUI.

**Comment by hessil** [comment]
Issue is still occurring for me

**Comment by gbeane** [comment]
> Issue is still occurring for me

Did you checkout this branch?

**Comment by hessil** [comment]
Yes

**Comment by hessil** [comment]
I've just deleted the cache and features for the project and am running that, this will take a while to check

**Comment by gbeane** [comment]
> I've just deleted the cache and features for the project and am running that, this will take a while to check

okay.  I was able to reproduce your exact error with the project you sent me with Dropbox, and this branch resolved it for me.

**Comment by hessil** [comment]
Clearing cache+features seemed to do the trick! Haven't got an error yet training on a second window size

**Review by SkepticRaven — APPROVED** [review]

**Comment by SkepticRaven** [comment]
Appears as though the test from the prior pull request broke the cache/feature folders. We should add "verify feature cache" as a feature request so that updating between versions goes a bit more smoothly.

**Comment by gbeane** [comment]
> Appears as though the test from the prior pull request broke the cache/feature folders. We should add "verify feature cache" as a feature request so that updating between versions goes a bit more smoothly.

so feature h5 files and other cache files include a version number that gets bumped when an incompatible change in file format is introduced so they are automatically re-created if they're an out of date format.

Unfortunately in this case a bug in the previous pull request (that was closed without merging) appears to have caused a problem with cached files.

**Comment by SkepticRaven** [comment]
> > Appears as though the test from the prior pull request broke the cache/feature folders. We should add "verify feature cache" as a feature request so that updating between versions goes a bit more smoothly.
> 
> so feature h5 files and other cache files include a version number that gets bumped when an incompatible change in file format is introduced so they are automatically re-created if they're an out of date format.
> 
> Unfortunately in this case a bug in the previous pull request (that was closed without merging) appears to have caused a problem with cached files.

Makes  sense. Probably not necessary then if its limited to potential changes breaking stuff.

**Pull request merged**
