### PR TITLE
Update library requirements.txt

### PR DESCRIPTION
**Pull request by SkepticRaven**
Updating the requirements.txt to not be 2-3 year old libraries.
There were a couple other changes to get compatibility working again.

Tests run at the beginning of this pull:
* Ran unittests: `python3 -m unittest discover -s /behavior-classifier/tests/`
  * `Ran 33 tests in 0.785s   OK`
* Ran `python3 initialize_project.py` on a project
* Opened the GUI from an updated gui-vm and trained a classifier

I don't have a bunch of dev environments to test, so these were all conducted inside singularity (running debian).
One of the fixed I needed to do (upgrade to shapely change) may address https://github.com/KumarLabJax/JABS-behavior-classifier/issues/5#issuecomment-1621725227
Also address https://github.com/KumarLabJax/JABS-behavior-classifier/issues/24

Would be good to have someone with a mac environment to share their experience.

### CODE REVIEW

**Comment by SkepticRaven** [comment]
Works successfully on windows 10 (python 3.10.11)

**Comment by SkepticRaven** [comment]
@dahhei tried to install the venv on a mac and discovered shiboken needed to be updated from 5 -> 6

**Comment by SkepticRaven** [comment]
This branch would have particularly benefited from having more coverage on unittests.
Given that I missed that one, I should probably click all the buttons on the gui and even run tests on the non-gui version to make sure things don't change before a merge.
New list of tests that should probably go through:
* Click all the buttons on gui
* Test multiple project pose versions (2, 3, 4, 5)
* Test command line interface (classify.py, initialize_project.py, and stats.py)

Also I upgraded the singularity gui vm from buster -> bookworm, so should make the non-gui one also be bookworm (not bullseye).

**Review by dahhei — APPROVED** [review]
The requirements.txt works without errors on my local M1 Macbook. Exporting a classifier also works fine on my end now.

**Comment by SkepticRaven** [comment]
A couple notes from testing/poking around:
* (Critical) Pause (after play) causes segfault ~50% of the time
  * Currently unclear cause, as threads seem to get closed correctly. It's happening after/during the repaint even after it stops
* (Minor) Text littered around the UI is now lighter compared to older versions
  * This may be linked to OS settings and may be limited to my Ubuntu host machine (not present in CentOS test)

**Comment by SkepticRaven** [comment]
Latest commit should clear the 2 issues above.
Remaining checks before merge:
* Confirm crash fix native on macs
* Test `stats.py`

**Pull request merged**
